import { NakshatraInfo } from './types';

export const NAKSHATRAS: NakshatraInfo[] = [
  {
    index: 1,
    name: 'Ashwini',
    cnName: '娄宿 (Ashwini)',
    ruler: 'Ketu',
    rulerCn: '计都 (Ketu)',
    deity: 'Ashvins',
    deityCn: '双马童神 (奇迹医者)',
    symbol: "Horse's Head",
    symbolCn: '马头',
    guna: 'Rajas',
    element: 'Earth',
    keywords: ['敏捷迅捷', '开创先驱', '疗愈本能', '热烈纯粹'],
    summary: '象征黎明初现与新生的爆发力，具有极快行动力和自我治愈本能，擅长迅速启动新项目与打破僵局。'
  },
  {
    index: 2,
    name: 'Bharani',
    cnName: '胃宿 (Bharani)',
    ruler: 'Venus',
    rulerCn: '金星 (Venus)',
    deity: 'Yama',
    deityCn: '阎摩 (正法死神与蜕变)',
    symbol: 'Yoni',
    symbolCn: '子宫 / 容器',
    guna: 'Rajas',
    element: 'Earth',
    keywords: ['孕育蜕变', '忍耐极限', '情感张力', '生死界限'],
    summary: '掌管孕育与极端的蜕变重生，承载巨大压力并在风暴后完成彻底蜕变，对生命深刻执着。'
  },
  {
    index: 3,
    name: 'Krittika',
    cnName: '昴宿 (Krittika)',
    ruler: 'Sun',
    rulerCn: '太阳 (Sun)',
    deity: 'Agni',
    deityCn: '阿耆尼 (火神)',
    symbol: 'Razor / Flame',
    symbolCn: '利刃 / 火焰',
    guna: 'Rajas',
    element: 'Fire',
    keywords: ['明晰利落', '去伪存真', '严谨批判', '王者魄力'],
    summary: '如剃刀般锋利的洞察力，以纯净烈火焚烧杂质，具备极高道德标准与直击要害的批判思维。'
  },
  {
    index: 4,
    name: 'Rohini',
    cnName: '毕宿 (Rohini)',
    ruler: 'Moon',
    rulerCn: '月亮 (Moon)',
    deity: 'Brahma / Prajapati',
    deityCn: '梵天 (创造之神)',
    symbol: 'Ox Cart / Chariot',
    symbolCn: '牛车 / 丰饶之辇',
    guna: 'Rajas',
    element: 'Earth',
    keywords: ['极致审美', '丰盛创造', '滋养繁衍', '魅力磁场'],
    summary: '月亮最喜爱的居所，极具审美天赋、物质丰盛与艺术创造力，具有天然的吸引力与温暖滋养磁场。'
  },
  {
    index: 5,
    name: 'Mrigashira',
    cnName: '觜宿 (Mrigashira)',
    ruler: 'Mars',
    rulerCn: '火星 (Mars)',
    deity: 'Soma',
    deityCn: '月神苏摩 (长生甘露)',
    symbol: "Deer's Head",
    symbolCn: '鹿头',
    guna: 'Tamas',
    element: 'Earth',
    keywords: ['求索寻觅', '敏锐灵动', '旅行探索', '纯真好奇'],
    summary: '永不停歇的知识与真理探索者，如灵鹿般对外界保持好奇与敏锐，擅长调研、求知与跨界探索。'
  },
  {
    index: 6,
    name: 'Ardra',
    cnName: '参宿 (Ardra)',
    ruler: 'Rahu',
    rulerCn: '罗睺 (Rahu)',
    deity: 'Rudra',
    deityCn: '鲁陀罗 (暴风雷霆之神)',
    symbol: 'Teardrop / Diamond',
    symbolCn: '泪滴 / 钻石',
    guna: 'Tamas',
    element: 'Water',
    keywords: ['风暴洗礼', '前沿科技', '毁灭与顿悟', '智性穿透'],
    summary: '象征泪水洗礼后的钻石般清澈，擅长在混乱和技术前沿中洞悉真理，极具突破旧规则的颠覆力。'
  },
  {
    index: 7,
    name: 'Punarvasu',
    cnName: '井宿 (Punarvasu)',
    ruler: 'Jupiter',
    rulerCn: '木星 (Jupiter)',
    deity: 'Aditi',
    deityCn: '阿底提 (宇宙母神/无限)',
    symbol: 'Bow and Quiver',
    symbolCn: '箭袋 / 回归之弓',
    guna: 'Sattva',
    element: 'Water',
    keywords: ['光辉复归', '仁慈宽厚', '百折不挠', '精神守护'],
    summary: '“光芒之重归”，象征射出之箭总能安全收回。具备极强的生命韧性与宽厚仁心，经历挫折总能优雅重返巅峰。'
  },
  {
    index: 8,
    name: 'Pushya',
    cnName: '鬼宿 (Pushya)',
    ruler: 'Saturn',
    rulerCn: '土星 (Saturn)',
    deity: 'Brihaspati',
    deityCn: '广博仙人 (众神之导师)',
    symbol: "Cow's Udder / Lotus",
    symbolCn: '牛之乳房 / 盛开莲花',
    guna: 'Tamas',
    element: 'Water',
    keywords: ['至尊吉祥', '智慧滋养', '稳固护持', '灵性觉照'],
    summary: '吠陀占星中公认最吉祥温厚的月宿，兼具木星的慈悲与土星的坚韧，擅长为他人提供无条件的滋养与庇护。'
  },
  {
    index: 9,
    name: 'Ashlesha',
    cnName: '柳宿 (Ashlesha)',
    ruler: 'Mercury',
    rulerCn: '水星 (Mercury)',
    deity: 'Nagas',
    deityCn: '那伽神蛇 (灵蛇与隐秘直觉)',
    symbol: 'Coiled Serpent',
    symbolCn: '盘绕之蛇',
    guna: 'Sattva',
    element: 'Water',
    keywords: ['昆达里尼能量', '隐秘洞察', '心理谋略', '深度催化'],
    summary: '深具灵蛇的深邃直觉与催眠般的影响力，擅长心理学、隐蔽调查与高维直觉，对人性的暗流一目了然。'
  },
  {
    index: 10,
    name: 'Magha',
    cnName: '星宿 (Magha)',
    ruler: 'Ketu',
    rulerCn: '计都 (Ketu)',
    deity: 'Pitris',
    deityCn: '历代先祖神灵 (祖荫传承)',
    symbol: 'Royal Throne',
    symbolCn: '王座 / 权杖',
    guna: 'Tamas',
    element: 'Water',
    keywords: ['祖荫血脉', '领袖王座', '尊严威仪', '使命传承'],
    summary: '天生自带高贵气场与家族祖荫庇佑，具备强烈的责任心与领袖风范，重视尊严、传统与传承。'
  },
  {
    index: 11,
    name: 'Purva Phalguni',
    cnName: '张宿 (Purva Phalguni)',
    ruler: 'Venus',
    rulerCn: '金星 (Venus)',
    deity: 'Bhaga',
    deityCn: '福佑之神 (财富与享乐)',
    symbol: 'Front Legs of Bed',
    symbolCn: '卧榻之柱 / 摇床',
    guna: 'Rajas',
    element: 'Water',
    keywords: ['浪漫激情', '艺术社交', '享乐恩赐', '创意绽放'],
    summary: '掌管人际温暖与浪漫创造力，懂得享受生活之美，具有天生的社交亲和力与艺术表现力。'
  },
  {
    index: 12,
    name: 'Uttara Phalguni',
    cnName: '翼宿 (Uttara Phalguni)',
    ruler: 'Sun',
    rulerCn: '太阳 (Sun)',
    deity: 'Aryaman',
    deityCn: '友善与契约之神',
    symbol: 'Back Legs of Bed',
    symbolCn: '稳固之床 / 结盟之柱',
    guna: 'Rajas',
    element: 'Fire',
    keywords: ['信义契约', '稳定奉献', '高贵护持', '君子同盟'],
    summary: '代表成熟的盟约与信义，愿意为长远承诺付出汗水，具有大局观与坚守正义的高尚品格。'
  },
  {
    index: 13,
    name: 'Hasta',
    cnName: '轸宿 (Hasta)',
    ruler: 'Moon',
    rulerCn: '月亮 (Moon)',
    deity: 'Savitr',
    deityCn: '萨维特神 (旭日初升创造者)',
    symbol: 'Open Hand',
    symbolCn: '张开的手掌',
    guna: 'Rajas',
    element: 'Fire',
    keywords: ['巧手妙术', '疗愈工匠', '敏捷幽默', '抓住机遇'],
    summary: '以双手创造奇迹的工匠宿，掌控精妙手艺、魔法般的执行力与敏捷机智，擅长把握转瞬即逝的良机。'
  },
  {
    index: 14,
    name: 'Chitra',
    cnName: '角宿 (Chitra)',
    ruler: 'Mars',
    rulerCn: '火星 (Mars)',
    deity: 'Vishwakarma',
    deityCn: '天界大建筑师 (神圣匠心)',
    symbol: 'Bright Jewel / Pearl',
    symbolCn: '璀璨宝石 / 珍珠',
    guna: 'Tamas',
    element: 'Fire',
    keywords: ['璀璨匠心', '结构设计', '建筑视觉', '独特个性'],
    summary: '如精心雕琢的宝石般光彩照人，具有极高的视觉审美、工程架构与设计天赋，不容许任何粗糙。'
  },
  {
    index: 15,
    name: 'Svati',
    cnName: '亢宿 (Svati)',
    ruler: 'Rahu',
    rulerCn: '罗睺 (Rahu)',
    deity: 'Vayu',
    deityCn: '风神伐由 (自由之风)',
    symbol: 'Young Plant in Wind',
    symbolCn: '风中嫩芽 / 珊瑚',
    guna: 'Tamas',
    element: 'Fire',
    keywords: ['独立自由', '柔韧灵动', '商贸外交', '自我绽放'],
    summary: '像风一样不可捉摸与追寻自由，极度懂得在逆境中像嫩芽般弯曲以避其锋芒，具备卓越的商业外交头脑。'
  },
  {
    index: 16,
    name: 'Vishakha',
    cnName: '氐宿 (Vishakha)',
    ruler: 'Jupiter',
    rulerCn: '木星 (Jupiter)',
    deity: 'Indra & Agni',
    deityCn: '因陀罗与火神 (王者与烈火)',
    symbol: 'Triumphal Arch',
    symbolCn: '凯旋门 / 分叉之枝',
    guna: 'Sattva',
    element: 'Fire',
    keywords: ['坚毅执念', '目标导向', '胜利凯旋', '跨越门槛'],
    summary: '具有不可动摇的目标感与决胜意志，不达目的誓不罢休，擅长在多重路径中锁定最终的胜利。'
  },
  {
    index: 17,
    name: 'Anuradha',
    cnName: '房宿 (Anuradha)',
    ruler: 'Saturn',
    rulerCn: '土星 (Saturn)',
    deity: 'Mitra',
    deityCn: '密多罗神 (友谊与光芒之神)',
    symbol: 'Lotus in Mud',
    symbolCn: '出泥莲花 / 胜利之钟',
    guna: 'Tamas',
    element: 'Earth',
    keywords: ['泥中绽放', '至诚友谊', '隐秘忠诚', '跨国灵修'],
    summary: '出淤泥而不染的高贵灵魂，擅长在冷峻现实中建立真诚深刻的盟友网络，具备隐秘的奉献精神。'
  },
  {
    index: 18,
    name: 'Jyeshtha',
    cnName: '心宿 (Jyeshtha)',
    ruler: 'Mercury',
    rulerCn: '水星 (Mercury)',
    deity: 'Indra',
    deityCn: '帝释天因陀罗 (众神之王)',
    symbol: 'Circular Amulet',
    symbolCn: '护身符 / 耳环',
    guna: 'Sattva',
    element: 'Earth',
    keywords: ['尊长霸气', '威权护盾', '深谋远虑', '独当一面'],
    summary: '“长者/尊贵之星”，具有天然的长者威严与承担风雨的霸气，擅长在危机中独当一面，捍卫领地。'
  },
  {
    index: 19,
    name: 'Mula',
    cnName: '尾宿 (Mula)',
    ruler: 'Ketu',
    rulerCn: '计都 (Ketu)',
    deity: 'Nirriti',
    deityCn: '迦梨/破灭母神 (根基解构者)',
    symbol: 'Tied Roots',
    symbolCn: '紧缚之树根',
    guna: 'Tamas',
    element: 'Air',
    keywords: ['直捣根源', '彻底归零', '深层灵性', '颠覆重构'],
    summary: '银河系中心的起源之宿，直击一切事物的核心本质。不畏惧推倒重来，能从最深的废墟中开创全新的灵性维度。'
  },
  {
    index: 20,
    name: 'Purva Ashadha',
    cnName: '箕宿 (Purva Ashadha)',
    ruler: 'Venus',
    rulerCn: '金星 (Venus)',
    deity: 'Apas',
    deityCn: '阿帕斯 (宇宙神圣之水)',
    symbol: "Fan / Winnowing Basket",
    symbolCn: '风扇 / 簸箕 (扬弃)',
    guna: 'Rajas',
    element: 'Air',
    keywords: ['不可战胜', '如水流动', '辩才无碍', '净化赋能'],
    summary: '“初胜之星”，拥有如水般无孔不入的渗透力与不屈的感染力，擅长化解顽石，在辩论与公众表达中极具魅力。'
  },
  {
    index: 21,
    name: 'Uttara Ashadha',
    cnName: '斗宿 (Uttara Ashadha)',
    ruler: 'Sun',
    rulerCn: '太阳 (Sun)',
    deity: 'Vishwadevas',
    deityCn: '普世十神 (宇宙普遍德行)',
    symbol: "Elephant's Tusk",
    symbolCn: '象牙 / 登高之床',
    guna: 'Sattva',
    element: 'Air',
    keywords: ['终极凯旋', '大公无私', '持久耐力', '普世正义'],
    summary: '代表最终的绝对胜利与坚固基石，以高尚品格和持之以恒的毅力奠定不可动摇的功业。'
  },
  {
    index: 22,
    name: 'Shravana',
    cnName: '女宿 (Shravana)',
    ruler: 'Moon',
    rulerCn: '月亮 (Moon)',
    deity: 'Vishnu',
    deityCn: '毗湿奴 (宇宙护持之神)',
    symbol: 'Ear / Three Footprints',
    symbolCn: '耳朵 / 三步足迹',
    guna: 'Rajas',
    element: 'Air',
    keywords: ['倾听智慧', '知识传承', '高维连接', '护持众生'],
    summary: '神圣倾听者，拥有接收天地高维灵感与倾听他人心声的天赋，擅长口口相传的学术研究与组织护持。'
  },
  {
    index: 23,
    name: 'Dhanishta',
    cnName: '虚宿 (Dhanishta)',
    ruler: 'Mars',
    rulerCn: '火星 (Mars)',
    deity: 'Ashta Vasus',
    deityCn: '八位丰盛光芒之神',
    symbol: 'Drum / Flute',
    symbolCn: '达玛茹战鼓 / 笛子',
    guna: 'Tamas',
    element: 'Ether',
    keywords: ['财富节奏', '韵律掌控', '宏大格局', '声名远扬'],
    summary: '“最富裕之星”，掌控宇宙的节拍与音律，对商业脉搏、财富运作与组织节奏有绝顶天赋，成就显著。'
  },
  {
    index: 24,
    name: 'Shatabhisha',
    cnName: '危宿 (Shatabhisha)',
    ruler: 'Rahu',
    rulerCn: '罗睺 (Rahu)',
    deity: 'Varuna',
    deityCn: '伐楼那 (宇宙海洋与天道之神)',
    symbol: 'Empty Circle / 100 Physicians',
    symbolCn: '百位神医 / 虚空之圆',
    guna: 'Tamas',
    element: 'Ether',
    keywords: ['百草神医', '隐士哲学', '星海探索', '破解迷局'],
    summary: '掌控百种疗愈之法与前沿未知的隐秘星宿，常有超越时代的科学家或哲学家特质，擅长治疗疑难绝症与破解死局。'
  },
  {
    index: 25,
    name: 'Purva Bhadrapada',
    cnName: '室宿 (Purva Bhadrapada)',
    ruler: 'Jupiter',
    rulerCn: '木星 (Jupiter)',
    deity: 'Aja Ekapada',
    deityCn: '独脚山羊神 (雷霆之光)',
    symbol: 'Front of Funeral Cot / Sword',
    symbolCn: '双面之人 / 灵修之火',
    guna: 'Sattva',
    element: 'Ether',
    keywords: ['雷霆烈火', '双重深邃', '狂热奉献', '精神涅槃'],
    summary: '深具双面性与极强精神烈火，能够为了崇高信念燃烧一切，擅长神秘学探究与深层精神净化。'
  },
  {
    index: 26,
    name: 'Uttara Bhadrapada',
    cnName: '壁宿 (Uttara Bhadrapada)',
    ruler: 'Saturn',
    rulerCn: '土星 (Saturn)',
    deity: 'Ahir Budhnya',
    deityCn: '深海神龙 (海底灵蛇守护者)',
    symbol: 'Back of Funeral Cot / Snake',
    symbolCn: '深海潜龙 / 慈悲沉静',
    guna: 'Tamas',
    element: 'Water',
    keywords: ['深海潜龙', '慈悲稳重', '精神定力', '大智若愚'],
    summary: '如深海潜龙般沉稳安详，拥有惊人的情绪定力、冥想直觉与慈悲心，能在混乱世界中保持内在平静。'
  },
  {
    index: 27,
    name: 'Revati',
    cnName: '奎宿 (Revati)',
    ruler: 'Mercury',
    rulerCn: '水星 (Mercury)',
    deity: 'Pushan',
    deityCn: '普善神 (旅者护送者与丰饶之神)',
    symbol: 'Fish / Pair of Fish',
    symbolCn: '双鱼 / 旅者手杖',
    guna: 'Sattva',
    element: 'Water',
    keywords: ['圆满归宿', '普度众生', '旅途守护', '超凡灵感'],
    summary: '黄道27宿的最终圆满归宿，拥有极纯粹的博爱慈悲与艺术灵感，擅长指引迷途旅者并带来终极平静。'
  }
];

export function getNakshatraByDegree(siderealDegree: number): { nakshatra: NakshatraInfo; pada: number; degreeInNakshatra: number } {
  const normDeg = ((siderealDegree % 360) + 360) % 360;
  const nakshatraSpan = 360 / 27; // 13.333333333 degrees (13°20')
  const index = Math.floor(normDeg / nakshatraSpan);
  const degreeInNakshatra = normDeg - index * nakshatraSpan;
  const padaSpan = nakshatraSpan / 4; // 3°20'
  const pada = Math.min(4, Math.floor(degreeInNakshatra / padaSpan) + 1);

  return {
    nakshatra: NAKSHATRAS[index % 27],
    pada,
    degreeInNakshatra
  };
}
