import { Compass, Heart, Briefcase, Coins, Activity, Moon, Users, ShieldAlert, Wand2, Clock } from "lucide-react";

export const CATEGORIES = [
  { id: "general", name: "综合运势", icon: Compass },
  { id: "love", name: "爱情与人际", icon: Heart },
  { id: "career", name: "事业与学业", icon: Briefcase },
  { id: "wealth", name: "财富运势", icon: Coins },
  { id: "health", name: "健康状态", icon: Activity },
  { id: "spiritual", name: "灵性成长", icon: Moon },
  { id: "family", name: "家庭与生活", icon: Users },
  { id: "crisis", name: "趋吉避凶", icon: ShieldAlert },
  { id: "decision", name: "抉择与指引", icon: Wand2 },
  { id: "past_future", name: "前世与未来", icon: Clock },
];

export const SPREAD_MODES = [
  {
    id: "single",
    name: "每日单牌",
    cardCount: 1,
    positions: ["核心指引"],
    description: "抽取一张牌，获取直接的指引",
  },
  {
    id: "yes_no",
    name: "是非牌阵",
    cardCount: 3,
    positions: ["现状", "阻碍/助力", "最终结果(是/否)"],
    description: '快速解答明确的"是与否"问题',
  },
  {
    id: "time",
    name: "圣三角牌阵",
    cardCount: 3,
    positions: ["过去", "现在", "未来"],
    description: "经典牌阵，分析事情的发展脉络",
  },
  {
    id: "mind_body_spirit",
    name: "身心灵牌阵",
    cardCount: 3,
    positions: ["身体状态", "心理状态", "精神指引"],
    description: "探索自我内在，寻求身心平衡",
  },
  {
    id: "four_elements",
    name: "四元素牌阵",
    cardCount: 4,
    positions: [
      "火(行动/热情)",
      "水(情感/人际)",
      "风(思想/沟通)",
      "土(物质/现实)",
    ],
    description: "从四个维度全面剖析现状",
  },
  {
    id: "relationship",
    name: "关系牌阵",
    cardCount: 4,
    positions: ["你的状态", "对方状态", "关系现状", "未来发展"],
    description: "专门用于分析两人关系与情感走向",
  },
  {
    id: "blind_spot",
    name: "盲点牌阵",
    cardCount: 4,
    positions: ["你知道的", "你不知道的", "别人知道的", "别人不知道的"],
    description: "打破认知局限，发现隐藏的问题",
  },
  {
    id: "past_life",
    name: "前世今生牌阵",
    cardCount: 5,
    positions: [
      "前世的影响",
      "前世的课题",
      "今生的现状",
      "今生的挑战",
      "未来的指引",
    ],
    description: "探索灵魂印记与宿命因果",
  },
  {
    id: "choice",
    name: "二选一牌阵",
    cardCount: 5,
    positions: [
      "现状",
      "选择A的走向",
      "选择B的走向",
      "选择A的结果",
      "选择B的结果",
    ],
    description: "面临抉择时，分析不同决定的结果",
  },
  {
    id: "crisis_avoidance",
    name: "危机预警牌阵",
    cardCount: 4,
    positions: [
      "即将面临的挑战/危机",
      "危机产生的原因",
      "如何规避/化解",
      "最终的走向",
    ],
    description: "预见未来的障碍与问题，并获取化解的指引",
  },
  {
    id: "career",
    name: "事业发展牌阵",
    cardCount: 5,
    positions: ["现状", "面临的挑战", "你的优势", "外部环境", "最终结果"],
    description: "深入分析工作、事业或学业的发展",
  },
  {
    id: "mirror",
    name: "人际镜像牌阵",
    cardCount: 5,
    positions: ["你的状态", "对方状态", "你们的互动", "潜在问题", "未来发展"],
    description: "深入剖析两人之间的互动模式与镜像关系",
  },
  {
    id: "chakra",
    name: "七脉轮牌阵",
    cardCount: 7,
    positions: [
      "海底轮(生存/根基)",
      "本我轮(情感/欲望)",
      "太阳轮(意志/力量)",
      "心轮(爱/同理)",
      "喉轮(表达/沟通)",
      "眉心轮(直觉/洞察)",
      "顶轮(灵性/智慧)",
    ],
    description: "深入分析个人能量状态与灵性发展",
  },
  {
    id: "hexagram",
    name: "六芒星牌阵",
    cardCount: 7,
    positions: ["过去", "现在", "未来", "建议", "环境", "阻碍", "结果"],
    description: "全面解析复杂事件的前因后果",
  },
  {
    id: "week",
    name: "一周运势牌阵",
    cardCount: 7,
    positions: ["周一", "周二", "周三", "周四", "周五", "周六", "周日"],
    description: "预测未来一周的每日运势走向",
  },
  {
    id: "tree_of_life",
    name: "生命之树牌阵",
    cardCount: 10,
    positions: [
      "最高理想",
      "创造力/智慧",
      "理解力",
      "仁慈/恩典",
      "力量/挑战",
      "美丽/核心",
      "本能/情感",
      "理智/沟通",
      "潜意识/基础",
      "现实/显化",
    ],
    description: "基于卡巴拉生命之树，进行深度的灵魂与现实剖析",
  },
  {
    id: "celtic_cross",
    name: "凯尔特十字",
    cardCount: 10,
    positions: [
      "现状",
      "挑战/阻碍",
      "潜在原因",
      "过去的影响",
      "目标/意识",
      "未来的走向",
      "自我态度",
      "环境/他人",
      "愿望/恐惧",
      "最终结果",
    ],
    description: "最经典的塔罗牌阵，提供极其详尽的分析",
  },
  {
    id: "zodiac",
    name: "黄道十二宫",
    cardCount: 12,
    positions: [
      "白羊(自我)",
      "金牛(财富)",
      "双子(沟通)",
      "巨蟹(家庭)",
      "狮子(创造/恋爱)",
      "处女(工作/健康)",
      "天秤(合作/伴侣)",
      "天蝎(疾厄/转化)",
      "射手(探索/学业)",
      "摩羯(事业/地位)",
      "水瓶(人际/愿景)",
      "双鱼(潜意识/隐秘)",
    ],
    description: "全方位预测年度运势或整体人生格局",
  },
  {
    id: "yearly",
    name: "流年运势牌阵",
    cardCount: 13,
    positions: [
      "1月",
      "2月",
      "3月",
      "4月",
      "5月",
      "6月",
      "7月",
      "8月",
      "9月",
      "10月",
      "11月",
      "12月",
      "年度核心主题",
    ],
    description: "预测未来一整年的月度运势起伏",
  },
];
